channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-ggpubr
  - r-vegan
  - bioconductor-phyloseq
  - r-dendextend
  - r-ggrepel
  - bioconductor-keggrest
  - r-stringi
